services:
  - type: web
    name: carecircle
    runtime: python
    repo: https://github.com/sharmila2719/carecircle-breast-cancer-agent
    branch: master
    buildCommand: pip install -r requirements.txt
    startCommand: python -m streamlit run streamlit_app.py --server.port $PORT --server.address 0.0.0.0 --server.headless true
    envVars:
      - key: PYTHON_VERSION
        value: "3.11"
